runeserver/app.py
from flask import (Flask, request, session, redirect, url_for, abort, render_template, flash)

from blueprints.fileserver import fs_page

app = Flask(__name__)  # create app instance
app.config.from_object(__name__)  # load config from this file ()

# load default config and override config from an environment variable
app.config.update(
   # DATABASE=os.path.join(app.root_path, 'common.db'),
    SECRET_KEY=b'_5#y2L"F4Q8z\n\xec]/',
    USERNAME='ino',
    PASSWORD='fin'
)

app.register_blueprint(fs_page)

runeserver/blueprints/error.py
from flask import Blueprint, render_template

error_page = Blueprint('error_page', __name__,
                        template_folder='templates')

"""ERROR HANDLER"""
@error_page.errorhandler(403)
def page_not_found(e):
    # note that we set the 403 status explicitly
    return render_template('403.html'), 403

runeserver/blueprints/fileserver.py
from flask import Blueprint, request, session, redirect, url_for, render_template, flash
from werkzeug.utils import secure_filename
from os import getcwd, path
from runeserver.utilities.extensions import allowed_file, file_extensions
from utilities import file_storage as fs
import Log as log

fs_page = Blueprint('fs_page', __name__, template_folder='templates')

CURRENT_DIR = getcwd()
UPLOAD_PATH = path.join(CURRENT_DIR,"runeserver/static/uploads")

log.DEBUG("UPLOAD DIR {}".format(UPLOAD_PATH))

"""VIEW FUNCTIONS"""
@fs_page.route('/', methods=['GET', 'POST'])
def main_menu():

    # go to the functions for these pages
    if request.method == 'POST':

        if request.form['uo'] == "upload_menu":
            return redirect(url_for('fs_page.upload_menu'))

        if request.form['uo'] == "view_uploads":
            return redirect(url_for("fs_page.upload_viewer"))
    #
    return render_template('main_menu.html', user="Guest")

@fs_page.route('/upload', methods=['GET', 'POST'])
def upload():
    error = ""
    if request.method == 'POST':
        if 'file' not in request.files:
            flash('No file')
            return redirect(request.url)
        file = request.files['file']

        if file.filename == '':
            flash('No selected file')
            return redirect(request.url)

        if file and allowed_file(file.filename):
            filename = secure_filename(file.filename)
            filename = "/" + filename
            # get correct path for type of file
            if fs.is_valid_file(filename, session['utype']):
                fs.touch_folder( UPLOAD_PATH)
                file.save(path.join( UPLOAD_PATH  + filename))
                # thank you screen
                return redirect(url_for('fs_page.uploaded_file', uploaded_file = filename))
            else:
                print(session['utype'])
                error = "invalid file type"

    return render_template('upload.html', error=error)

@fs_page.route('/upload_menu', methods=['GET', 'POST'])
def upload_menu():
    if request.method == 'POST':
        session['utype'] = request.form['utype']
        return redirect(url_for('fs_page.upload'))

    return render_template('uploadmenu.html')

# thank you screen
@fs_page.route('/uploaded')
def uploaded_file(uploaded_file: str):
    print("Uploaded file: ", uploaded_file)
    fpath = fs.get_upload_path(uploaded_file)
    return render_template('uploaded.html')


@fs_page.route('/upload_viewer', methods=['GET', 'POST'])
def upload_viewer():
    if request.method == 'GET':
        files = fs.find_image_files( UPLOAD_PATH)
        files.extend(fs.find_video_files(UPLOAD_PATH))
        return render_template('upload_viewer.html', user="Guest", files=files)


@fs_page.route('/display/<filename>')
def display_video(filename):
	print('display_video filename: ' + filename)
	return redirect(url_for('static', filename='uploads/' + filename), code=301)


@fs_page.route('/video_viewer', methods=['POST'])
def video_viewer():
    return render_template(
        'video_viewer.html',
        filename=request.form['vid_fn'],
        enctype=file_extensions.video_html_encodings.get(fs.get_ext(request.form['vid_fn']))
    )

runeserver/templates/layout.html
<!doctype html>
<html>
<head>
{% block head %}
<link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
<title> RuneServer </title>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
{% endblock %}
</head>
<body>

<table>

  <tr>
  <h1 class="title_banner">
    {% block title %}
    RUNE SERVER
    {% endblock %}  
  </h1>
  </tr>
  <tr>

    <div id="content">{% block content %}{% endblock %}</div>
  </tr> 
  <tr>
    <div id="footer">
      {% block footer %}
      &copy;
      <a href="{{url_for('fs_page.upload_menu')}}">
        Home
      </a>
      {% endblock %}
      </div>
  </tr> 
</table>

</body>
</html>

runeserver/templates/login.html
{% extends "layout.html" %}
{% block body %}
<h2>Login</h2>
{% if error %}<p class=error><strong>Error:</strong> {{ error }}{% endif %}
<form action="{{ url_for('login') }}" method=post>
<dl>
<dt>Username:
<dd><input type=text name=username>
<dt>Password:
<dd><input type=password name=password>
<dd><input type=submit value=Login>
</dl>
</form>
{% endblock %}

runeserver/templates/main_menu.html
{% extends 'layout.html'%}

{% block title %}
 Main Menu:
{% endblock %}

{% block content %}

<h1>Welcome to rune server</h1>


 <form method=post enctype=multipart/form-data>

<input type=submit name="uo" value="upload_menu">
<input  type=submit name="uo" value="view_uploads">

 </form>

<script>

</script>

{% endblock %}
</html>

runeserver/templates/title_banner.html
<h1 class="title_banner">hd: {{ title }} </h1>

runeserver/templates/upload.html
    <!doctype html>
    <title>Upload new File</title>
    <h1>Upload new File</h1>
    <div id="attention">
        <p id="error">{{error}}</p>

    </div>
    <form method=post enctype=multipart/form-data>
      <input type=file name=file>
      <input type=submit value=Upload>
    </form>


    <!-- Upload MENU-->

runeserver/templates/upload_viewer.html
{% extends "layout.html"%}

{% block content %}
<div id="imgs"></div>

{% for image in files %}

    <div class="thumbnail_selector"><img class="thumbnail" src="{{image}}" >
    
    <form method=post action="/video_viewer" enctype=multipart/form-data>
        <input type=submit name="vid_fn" value={{image}}>
    </form>
    </div>
{% endfor %}

{% endblock %}
{% block footer %}
<script>
var option = 'enlarge';
$(".thumbnail").click(function(){

if (option === 'enlarge'){
//$.post($(this).attr('src'));
    if($(this).width === 'auto'){
        $(this).width('10%');
    } else {
        $(this).height('auto');
        $(this).width('auto');
    }

//    $.post("viewer.html",{source : $(this).src});
}

});

</script>

{% endblock %}

</html>

runeserver/templates/uploaded.html
<!doctype html>
<title>Complete</title>
<h1 style="color:purple;">Upload successful</h1>

<a href="/">HOME</a>


    <!-- Upload MENU Response-->

runeserver/templates/uploadmenu.html
{% extends 'layout.html'%}

{% block title %}
    upload menu
{% endblock %}

{% block content %}

<form method=post enctype=multipart/form-data>
    <input type=submit name=utype value="image"><br>
    <input type=submit name=utype value="text"><br>
    <input type=submit name=utype value="video"><br>
    <input type=submit name=utype value="misc"><br>

</form>
{% endblock %}

runeserver/templates/video_viewer.html
{% extends "layout.html"%}

{% block content %}

{% if filename %}
	<div style="margin: 10px auto;">
		<video autoplay="autoplay" controls="controls" preload="preload">
			<source src="{{ url_for('fs_page.display_video', filename=filename) }}" type={{enctype}}></source>
		</video>
	</div>
{% endif %}

{% endblock %}